### PR TITLE
two fixes.

### PR DESCRIPTION
**Pull request by mattn**
Thanks to your vimdb.
- possible to work on windows.
- possible to work in non-english loacles.

Thanks.

### CODE REVIEW

**Comment by cldwalker** [comment]
Thanks for the windows fix! 

As for the encoding fix, I'm not sure I understand. Shouldn't each user [set their $LC_CTYPE en variable](http://blog.grayproductions.net/articles/ruby_19s_three_default_encodings) to get their desired encoding? Why set ISO-8859-1 for everybody? Is this because vim only comes with an english index.txt?

**Comment by mattn** [comment]
options.txt contains latin1 characters. When encoding is DBCS(double byte character set), the character make confuse for leading byte of multibyte. On ruby19, in my environment, external_encoding is Windows-31J. So if the file contains un-expected characters, it will raise error.

**Comment by mattn** [comment]
Andalso, most windows people does not set LC_CTYPE environment variable.

**Comment by mattn** [comment]
Ah, sorry. It is not needed.

**Comment by mattn** [comment]
On my environment, I install japanese translated help files. Maybe I see the error before specify `-N -u NONE`.
Sorry.

Please cherry-pick only first commit.

**Comment by cldwalker** [comment]
No worries. Thanks for the explanation. I may still have to force encode ISO-8859-1 for users who don't know how to install their language help files.

As a side tip, if your vimdb tables have trouble displaying japanese, try using hirb-unicode and require it in your ~/.vimdbrc

**Comment by mattn** [comment]
Hmm, it won't work correctly. vimdb specify search pattern in english text

https://github.com/cldwalker/vimdb/blob/master/lib/vimdb/commands.rb#L18

``` ruby
lines = File.read(file)[/={10,}\n5. EX commands.*/m].split("\n")
```

In japanese translated help file, it's not "EX commands".

**Comment by cldwalker** [comment]
Ok. So multi-language support seems difficult for now. I'm open to patches to make it work later. We could have locale files to make this work. I've done this before [with another project](https://github.com/cldwalker/ripl-i18n/tree/master/lib/ripl/i18n/locales).

So using `Encoding.find('ISO-8859-1')` does render english for you, correct? If so, I will use it for now.

**Comment by mattn** [comment]
> So using Encoding.find('ISO-8859-1') does render english for you, correct? If so, I will use it for now.

No need to add any `Encoding.xxx` hack to read english text. `-N -u NONE` make it. :)

**Comment by mattn** [comment]
Andalso I changed `-c` to `--cmd`. It will make vimdb faster! :)

**Comment by cldwalker** [comment]
Pulled in windows fix.

**Pull request closed without merging**
